// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providerwire

import (
	"github.com/labstack/echo/v4"
	"github.com/sonymuhamad/todo-app/httpserver"
	"github.com/sonymuhamad/todo-app/pkg"
	"github.com/sonymuhamad/todo-app/repository"
	"github.com/sonymuhamad/todo-app/usecase"
)

// Injectors from httpserver.go:

func InitializeHttpServer() *echo.Echo {
	envConfig := pkg.LoadEnvConfig()
	db := provideGormSQLDatabase(envConfig)
	post := repository.NewPost(db)
	usecasePost := usecase.NewPost(post)
	handler := httpserver.NewHandlerWithWire(usecasePost)
	echoEcho := provideHttpServer(envConfig, handler)
	return echoEcho
}

// httpserver.go:

func provideHttpServer(cfg pkg.EnvConfig, h *httpserver.Handler) *echo.Echo {
	r := httpserver.InitRouter(cfg, h)

	return r
}
